<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Skladiste.SharedKernel\Skladiste.SharedKernel.csproj" />
    <ProjectReference Include="..\Skladiste.Proizvodi\Skladiste.Proizvodi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
